import { Tile, TileType, CharacterConfig, CharacterRole, ShopItem } from './types';

export const BOARD_SIZE = 32;
export const WINNING_GOLD = 4000; // Increased due to larger board

export const INITIAL_RESOURCES = {
  gold: 800, // Slightly increased starting gold
  water: 100,
  energy: 50,
  materials: 20
};

export const CHARACTERS_CONFIG: CharacterConfig[] = [
  { 
    id: CharacterRole.BUILDER, 
    name: { ar: 'المقاول', en: 'The Builder' }, 
    desc: { ar: 'خبير في البناء والتطوير', en: 'Expert in construction and upgrades' }, 
    bonus: { ar: 'خصم 30% على التطوير', en: '30% Discount on Upgrades' },
    color: 'bg-orange-600'
  },
  { 
    id: CharacterRole.EXPLORER, 
    name: { ar: 'المستكشف', en: 'The Explorer' }, 
    desc: { ar: 'يعشق المغامرة والمجهول', en: 'Loves adventure and the unknown' }, 
    bonus: { ar: 'لا يتأثر بالمستنقعات', en: 'Immune to Swamps' },
    color: 'bg-green-600' 
  },
  { 
    id: CharacterRole.MERCHANT, 
    name: { ar: 'التاجر', en: 'The Merchant' }, 
    desc: { ar: 'سيد التجارة والمال', en: 'Master of trade and coin' }, 
    bonus: { ar: '+50% ذهب عند المرور بالبداية', en: '+50% Gold at Start' },
    color: 'bg-purple-600' 
  },
  { 
    id: CharacterRole.POLITICIAN, 
    name: { ar: 'السياسي', en: 'The Politician' }, 
    desc: { ar: 'ذو نفوذ وعلاقات', en: 'Influential and connected' }, 
    bonus: { ar: 'يربح دائماً في المبارزات', en: 'Always wins Duels' },
    color: 'bg-red-600' 
  }
];

export const SHOP_ITEMS: ShopItem[] = [
  { id: 'skin_gold', type: 'skin', name: { ar: 'الزي الذهبي', en: 'Golden Outfit' }, cost: 1000, icon: '👑' },
  { id: 'skin_bedouin', type: 'skin', name: { ar: 'زي البدو', en: 'Bedouin Robes' }, cost: 500, icon: '🧣' },
  { id: 'map_night', type: 'map', name: { ar: 'ليالي الصحراء', en: 'Desert Nights' }, cost: 2000, icon: '🌙' },
  { id: 'map_oasis', type: 'map', name: { ar: 'الواحة الخضراء', en: 'Green Oasis' }, cost: 1500, icon: '🌴' },
];

export const INITIAL_BOARD: Tile[] = [
  { id: 0, type: TileType.START, name: 'START', description: 'Collect Salary' },
  { id: 1, type: TileType.CITY, name: 'Damascus', price: 100, rent: 20, level: 1 },
  { id: 2, type: TileType.SWAMP, name: 'SWAMP_QUICKSAND', description: 'Stuck' },
  { id: 3, type: TileType.CITY, name: 'Baghdad', price: 120, rent: 25, level: 1 },
  { id: 4, type: TileType.CITY, name: 'Sanaa', price: 110, rent: 22, level: 1 },
  { id: 5, type: TileType.CITY, name: 'Cairo', price: 150, rent: 30, level: 1 },
  { id: 6, type: TileType.TAX, name: 'TAX_SULTAN', description: 'Pay Gold' },
  { id: 7, type: TileType.CITY, name: 'Alexandria', price: 140, rent: 28, level: 1 },
  { id: 8, type: TileType.ORACLE, name: 'ORACLE_SAGE', description: 'AI Oracle' },
  { id: 9, type: TileType.CITY, name: 'Riyadh', price: 160, rent: 35, level: 1 },
  { id: 10, type: TileType.JAIL, name: 'JAIL', description: 'Skip Turn' },
  { id: 11, type: TileType.CITY, name: 'Dubai', price: 200, rent: 50, level: 1 },
  { id: 12, type: TileType.SWAMP, name: 'SWAMP_MIRAGE', description: 'Lost' },
  { id: 13, type: TileType.CITY, name: 'Doha', price: 180, rent: 40, level: 1 },
  { id: 14, type: TileType.CITY, name: 'Kuwait', price: 170, rent: 38, level: 1 },
  { id: 15, type: TileType.CITY, name: 'Muscat', price: 130, rent: 26, level: 1 },
  { id: 16, type: TileType.ORACLE, name: 'ORACLE_LIB', description: 'Seek Knowledge' },
  { id: 17, type: TileType.CITY, name: 'Petra', price: 150, rent: 30, level: 1 },
  { id: 18, type: TileType.CITY, name: 'Beirut', price: 140, rent: 28, level: 1 },
  { id: 19, type: TileType.CITY, name: 'Mecca', price: 300, rent: 70, level: 1 },
  // --- New 32-Tile Content ---
  { id: 20, type: TileType.CITY, name: 'Jerusalem', price: 220, rent: 55, level: 1 },
  { id: 21, type: TileType.TREASURE, name: 'TREASURE_CAVE', description: 'Hidden Loot' },
  { id: 22, type: TileType.CITY, name: 'Casablanca', price: 190, rent: 45, level: 1 },
  { id: 23, type: TileType.CITY, name: 'Rabat', price: 180, rent: 42, level: 1 },
  { id: 24, type: TileType.SWAMP, name: 'SWAMP_SANDSTORM', description: 'Delays' },
  { id: 25, type: TileType.CITY, name: 'Tunis', price: 160, rent: 35, level: 1 },
  { id: 26, type: TileType.TAX, name: 'TAX_GUILD', description: 'Merchant Tax' },
  { id: 27, type: TileType.CITY, name: 'Algiers', price: 170, rent: 38, level: 1 },
  { id: 28, type: TileType.CITY, name: 'Manama', price: 180, rent: 40, level: 1 },
  { id: 29, type: TileType.CITY, name: 'Granada', price: 250, rent: 60, level: 1 },
  { id: 30, type: TileType.CITY, name: 'Cordoba', price: 240, rent: 58, level: 1 },
  { id: 31, type: TileType.SWAMP, name: 'SWAMP_EMPTY_QUARTER', description: 'Dangerous' },
];

export const TRANSLATIONS = {
  ar: {
    gameTitle: "حضارة الرمال",
    subTitle: "لعبة لوحية استراتيجية",
    play: "لعب",
    events: "الأحداث",
    eventsTitle: "الأحداث الجارية",
    alliance: "التحالف",
    shop: "المتجر",
    social: "المجتمع",
    guide: "الدليل",
    settings: "الإعدادات",
    gameLog: "سجل اللعبة",
    
    // Actions
    upgrade: "تطوير المبنى",
    upgradeCost: "تكلفة التطوير",
    level: "مستوى",
    duel: "مبارزة",
    duelWon: "فاز بالمبارزة!",
    duelLost: "خسر المبارزة",
    stuckSwamp: "عالق في المستنقع",
    swampEffect: "خسرت الحركة في الدور القادم!",

    // Alliance
    createAlliance: "إنشاء تحالف",
    joinAlliance: "انضم لتحالف",
    allianceName: "اسم التحالف",
    leaveAlliance: "مغادرة",
    donate: "تبرع",
    treasury: "الخزينة",
    members: "الأعضاء",
    technology: "التكنولوجيا",
    techTrade: "طرق التجارة",
    techDefense: "التحصينات",
    allianceEvents: "أحداث التحالف",
    mission1: "السيطرة على 5 مدن",
    mission2: "جمع 10,000 ذهب",
    donateMsg: "تبرع للتحالف",
    
    // Modes
    modeSelect: "اختر نمط اللعب",
    modePvE: "ضد الحاسوب",
    modeLocalPvP: "لاعب ضد لاعب (جهاز واحد)",
    modeOnlinePvP: "ضد صديق (اونلاين)",
    
    // Shop
    shopTitle: "سوق المدينة",
    skins: "الأزياء",
    maps: "الخرائط",
    buy: "شراء",
    owned: "مملوك",
    equip: "تجهيز",
    equipped: "مجهز",
    
    // General
    back: "عودة",
    start: "ابدأ",
    language: "اللغة",
    targetGold: "هدف الذهب",
    sound: "الصوت",
    chooseLeader: "اختر قائدك",
    turn: "دور",
    status: "الحالة",
    pass: "تخطى",
    payRent: "دفع إيجار",
    jailMsg: "في السجن!",
    freeMsg: "حر طليق!",
    win: "نصر!",
    playAgain: "العب مجدداً",
    finalStats: "الإحصائيات النهائية",
    properties: "الممتلكات",
    gold: "ذهب",
    water: "ماء",
    energy: "طاقة",
    materials: "مواد",
    oracleSpeaks: "الحكيم يتحدث",
    acceptFate: "اقبل المصير",
    rolled: "رمى",
    treasureFound: "كنز!",
    treasureMsg: "وجدت كنزاً مخفياً!",
    
    // Map
    START: "البداية",
    SWAMP_QUICKSAND: "الرمال المتحركة",
    SWAMP_MIRAGE: "وادي السراب",
    SWAMP_SANDSTORM: "عاصفة رملية",
    SWAMP_EMPTY_QUARTER: "الربع الخالي",
    TAX_SULTAN: "ضريبة السلطان",
    TAX_GUILD: "نقابة التجار",
    ORACLE_SAGE: "الحكيم",
    JAIL: "السجن",
    ORACLE_LIB: "المكتبة",
    TREASURE_CAVE: "كهف العجائب",

    // Cities
    Jerusalem: "القدس",
    Casablanca: "الدار البيضاء",
    Rabat: "الرباط",
    Tunis: "تونس",
    Algiers: "الجزائر",
    Manama: "المنامة",
    Granada: "غرناطة",
    Cordoba: "قرطبة",
    Damascus: "دمشق",
    Baghdad: "بغداد",
    Sanaa: "صنعاء",
    Cairo: "القاهرة",
    Alexandria: "الإسكندرية",
    Riyadh: "الرياض",
    Dubai: "دبي",
    Doha: "الدوحة",
    Kuwait: "الكويت",
    Muscat: "مسقط",
    Petra: "البتراء",
    Beirut: "بيروت",
    Mecca: "مكة",

    // Reset / Settings
    resetGame: "إعادة اللعب",
    voteResetTitle: "تصويت للإعادة",
    voteResetMsg: "هل توافق على إعادة تشغيل اللعبة؟",
    agree: "موافق",
    decline: "رفض",
    voteRejected: "تم رفض التصويت",
    gameResetInfo: "تم إعادة ضبط اللعبة",
  },
  en: {
    gameTitle: "Civilization of Sands",
    subTitle: "A Strategic Board Game",
    play: "Play",
    events: "Events",
    eventsTitle: "Live Events",
    alliance: "Alliance",
    shop: "Shop",
    social: "Social",
    guide: "Guide",
    settings: "Settings",
    gameLog: "Game Log",

    upgrade: "Upgrade Building",
    upgradeCost: "Upgrade Cost",
    level: "Level",
    duel: "Duel",
    duelWon: "Won the Duel!",
    duelLost: "Lost the Duel",
    stuckSwamp: "Stuck in Swamp",
    swampEffect: "Movement reduced next turn!",

    createAlliance: "Create Alliance",
    joinAlliance: "Join Alliance",
    allianceName: "Alliance Name",
    leaveAlliance: "Leave",
    donate: "Donate",
    treasury: "Treasury",
    members: "Members",
    technology: "Technology",
    techTrade: "Trade Routes",
    techDefense: "Fortifications",
    allianceEvents: "Alliance Events",
    mission1: "Control 5 Cities",
    mission2: "Collect 10,000 Gold",
    donateMsg: "Donate to Alliance",

    modeSelect: "Select Game Mode",
    modePvE: "Vs CPU",
    modeLocalPvP: "Vs Player (Local)",
    modeOnlinePvP: "Vs Friend (Online)",

    shopTitle: "City Market",
    skins: "Skins",
    maps: "Maps",
    buy: "Buy",
    owned: "Owned",
    equip: "Equip",
    equipped: "Equipped",

    back: "Back",
    start: "Start",
    language: "Language",
    targetGold: "Winning Gold Target",
    sound: "Sound Effects",
    chooseLeader: "Choose Your Leader",
    turn: "TURN",
    status: "STATUS",
    pass: "Pass",
    payRent: "Pay Rent",
    jailMsg: "In Jail!",
    freeMsg: "Is Free!",
    win: "VICTORY!",
    playAgain: "Play Again",
    finalStats: "Final Stats",
    properties: "Properties",
    gold: "Gold",
    water: "Water",
    energy: "Energy",
    materials: "Materials",
    oracleSpeaks: "The Oracle Speaks",
    acceptFate: "Accept Fate",
    rolled: "rolled",
    treasureFound: "Treasure Found!",
    treasureMsg: "You found hidden loot!",

    START: "Start",
    SWAMP_QUICKSAND: "Quicksand",
    SWAMP_MIRAGE: "Mirage Valley",
    SWAMP_SANDSTORM: "Sandstorm",
    SWAMP_EMPTY_QUARTER: "The Empty Quarter",
    TAX_SULTAN: "Sultan's Tax",
    TAX_GUILD: "Merchant Guild",
    ORACLE_SAGE: "The Sage",
    JAIL: "Dungeon",
    ORACLE_LIB: "Library",
    TREASURE_CAVE: "Cave of Wonders",

    Jerusalem: "Jerusalem",
    Casablanca: "Casablanca",
    Rabat: "Rabat",
    Tunis: "Tunis",
    Algiers: "Algiers",
    Manama: "Manama",
    Granada: "Granada",
    Cordoba: "Cordoba",
    Damascus: "Damascus",
    Baghdad: "Baghdad",
    Sanaa: "Sanaa",
    Cairo: "Cairo",
    Alexandria: "Alexandria",
    Riyadh: "Riyadh",
    Dubai: "Dubai",
    Doha: "Doha",
    Kuwait: "Kuwait",
    Muscat: "Muscat",
    Petra: "Petra",
    Beirut: "Beirut",
    Mecca: "Mecca",

    resetGame: "Reset Game",
    voteResetTitle: "Restart Vote",
    voteResetMsg: "Do you agree to restart the game?",
    agree: "Agree",
    decline: "Decline",
    voteRejected: "Restart Rejected",
    gameResetInfo: "Game has been reset",
  }
};