import { Tile, TileType, CharacterConfig, CharacterRole, ShopItem } from './types';

export const BOARD_SIZE = 20;
export const WINNING_GOLD = 2500;

export const INITIAL_RESOURCES = {
  gold: 500,
  water: 100,
  energy: 50,
  materials: 20
};

export const CHARACTERS_CONFIG: CharacterConfig[] = [
  { 
    id: CharacterRole.BUILDER, 
    name: { ar: 'المقاول', en: 'The Builder' }, 
    desc: { ar: 'خبير في البناء والتطوير', en: 'Expert in construction and upgrades' }, 
    bonus: { ar: 'خصم 20% على الشراء والتطوير', en: '20% Discount on Buy/Upgrade' },
    color: 'bg-orange-600'
  },
  { 
    id: CharacterRole.EXPLORER, 
    name: { ar: 'المستكشف', en: 'The Explorer' }, 
    desc: { ar: 'يعشق المغامرة والمجهول', en: 'Loves adventure and the unknown' }, 
    bonus: { ar: '+50% موارد من الواحات والأحداث', en: '+50% Resources from Oasis/Events' },
    color: 'bg-green-600' 
  },
  { 
    id: CharacterRole.MERCHANT, 
    name: { ar: 'التاجر', en: 'The Merchant' }, 
    desc: { ar: 'سيد التجارة والمال', en: 'Master of trade and coin' }, 
    bonus: { ar: '+50% ذهب عند المرور بالبداية', en: '+50% Gold at Start' },
    color: 'bg-purple-600' 
  },
  { 
    id: CharacterRole.POLITICIAN, 
    name: { ar: 'السياسي', en: 'The Politician' }, 
    desc: { ar: 'ذو نفوذ وعلاقات', en: 'Influential and connected' }, 
    bonus: { ar: 'حصانة 50% من الضرائب', en: '50% Tax Immunity' },
    color: 'bg-red-600' 
  }
];

export const SHOP_ITEMS: ShopItem[] = [
  { id: 'skin_gold', type: 'skin', name: { ar: 'الزي الذهبي', en: 'Golden Outfit' }, cost: 1000, icon: '👑' },
  { id: 'skin_bedouin', type: 'skin', name: { ar: 'زي البدو', en: 'Bedouin Robes' }, cost: 500, icon: '🧣' },
  { id: 'map_night', type: 'map', name: { ar: 'ليالي الصحراء', en: 'Desert Nights' }, cost: 2000, icon: '🌙' },
  { id: 'map_oasis', type: 'map', name: { ar: 'الواحة الخضراء', en: 'Green Oasis' }, cost: 1500, icon: '🌴' },
];

export const INITIAL_BOARD: Tile[] = [
  { id: 0, type: TileType.START, name: 'START', description: 'Collect Salary' },
  { id: 1, type: TileType.CITY, name: 'Damascus', price: 100, rent: 20, level: 1 },
  { id: 2, type: TileType.EVENT, name: 'EVENT_STORM', description: 'Event' },
  { id: 3, type: TileType.CITY, name: 'Baghdad', price: 120, rent: 25, level: 1 },
  { id: 4, type: TileType.OASIS, name: 'OASIS_PALM', description: 'Gain Water' },
  { id: 5, type: TileType.CITY, name: 'Cairo', price: 150, rent: 30, level: 1 },
  { id: 6, type: TileType.TAX, name: 'TAX_SULTAN', description: 'Pay Gold' },
  { id: 7, type: TileType.CITY, name: 'Alexandria', price: 140, rent: 28, level: 1 },
  { id: 8, type: TileType.ORACLE, name: 'ORACLE_SAGE', description: 'AI Oracle' },
  { id: 9, type: TileType.CITY, name: 'Riyadh', price: 160, rent: 35, level: 1 },
  { id: 10, type: TileType.JAIL, name: 'JAIL', description: 'Skip Turn' },
  { id: 11, type: TileType.CITY, name: 'Dubai', price: 200, rent: 50, level: 1 },
  { id: 12, type: TileType.EVENT, name: 'EVENT_CARAVAN', description: 'Trade' },
  { id: 13, type: TileType.CITY, name: 'Doha', price: 180, rent: 40, level: 1 },
  { id: 14, type: TileType.OASIS, name: 'OASIS_WELL', description: 'Refill Energy' },
  { id: 15, type: TileType.CITY, name: 'Muscat', price: 130, rent: 26, level: 1 },
  { id: 16, type: TileType.ORACLE, name: 'ORACLE_LIB', description: 'Seek Knowledge' },
  { id: 17, type: TileType.CITY, name: 'Petra', price: 150, rent: 30, level: 1 },
  { id: 18, type: TileType.TAX, name: 'TAX_WATER', description: 'Lose Water' },
  { id: 19, type: TileType.CITY, name: 'Mecca', price: 250, rent: 60, level: 1 }
];

export const TRANSLATIONS = {
  ar: {
    gameTitle: "حضارة الرمال",
    subTitle: "لعبة لوحية استراتيجية",
    play: "لعب",
    events: "الأحداث",
    eventsTitle: "الأحداث الجارية",
    alliance: "التحالف",
    shop: "المتجر",
    social: "المجتمع",
    guide: "الدليل",
    settings: "الإعدادات",
    gameLog: "سجل اللعبة",
    
    // Alliance
    createAlliance: "إنشاء تحالف",
    joinAlliance: "انضم لتحالف",
    allianceName: "اسم التحالف",
    leaveAlliance: "مغادرة",
    donate: "تبرع",
    treasury: "الخزينة",
    members: "الأعضاء",
    level: "المستوى",
    technology: "التكنولوجيا",
    techTrade: "طرق التجارة",
    techDefense: "التحصينات",
    upgrade: "ترقية",
    allianceEvents: "أحداث التحالف",
    mission1: "السيطرة على 5 مدن",
    mission2: "جمع 10,000 ذهب",
    donateMsg: "تبرع للتحالف",
    
    // Modes
    modeSelect: "اختر نمط اللعب",
    modePvE: "ضد الحاسوب",
    modeLocalPvP: "لاعب ضد لاعب (جهاز واحد)",
    modeOnlinePvP: "ضد صديق (اونلاين)",
    
    // Online
    createRoom: "إنشاء غرفة",
    joinRoom: "انضمام لغرفة",
    enterCode: "أدخل كود الغرفة",
    waitingForPlayer: "بانتظار اللاعب...",
    roomCode: "كود الغرفة:",
    shareCode: "شارك هذا الكود مع صديقك",
    
    // Shop
    shopTitle: "سوق المدينة",
    skins: "الأزياء",
    maps: "الخرائط",
    buy: "شراء",
    owned: "مملوك",
    equip: "تجهيز",
    equipped: "مجهز",
    
    // Social
    chat: "الدردشة",
    globalChat: "الدردشة العامة",
    
    // Guide
    howToPlay: "كيفية اللعب",
    rule1: "ارمي النرد وتحرك عبر المدن.",
    rule2: "اشترِ المدن التي تقف عليها لتحصيل الإيجار.",
    rule3: "احذر من العواصف والضرائب!",
    rule4: "استخدم قدرات شخصيتك للفوز.",
    
    // General
    back: "عودة",
    start: "ابدأ",
    language: "اللغة",
    targetGold: "هدف الذهب",
    sound: "الصوت",
    saveReturn: "حفظ وعودة",
    chooseLeader: "اختر قائدك",
    turn: "دور",
    status: "الحالة",
    rollDice: "ارمي النرد",
    pass: "تخطى",
    payRent: "دفع إيجار",
    taxPaid: "تم دفع الضريبة",
    jailMsg: "في السجن!",
    freeMsg: "حر طليق!",
    win: "نصر!",
    lost: "إفلاس",
    playAgain: "العب مجدداً",
    finalStats: "الإحصائيات النهائية",
    properties: "الممتلكات",
    gold: "ذهب",
    water: "ماء",
    energy: "طاقة",
    materials: "مواد",
    eventStorm: "عاصفة رملية",
    eventCaravan: "قافلة تجارية",
    eventMirage: "سراب",
    eventTreasure: "كنز",
    oracleSpeaks: "الحكيم يتحدث",
    acceptFate: "اقبل المصير",
    buyWater: "شراء ماء",
    buyMat: "شراء مواد",
    guideCaravan: "إرشاد القافلة",
    dismiss: "صرف",
    cost: "التكلفة",
    rent: "الإيجار",
    startBonus: "مكافأة البداية",
    rolled: "رمى",
    START: "البداية",
    EVENT_STORM: "عاصفة",
    OASIS_PALM: "واحة النخيل",
    TAX_SULTAN: "ضريبة السلطان",
    ORACLE_SAGE: "الحكيم",
    JAIL: "السجن",
    EVENT_CARAVAN: "قافلة",
    OASIS_WELL: "البئر",
    ORACLE_LIB: "المكتبة",
    TAX_WATER: "ضريبة الماء"
  },
  en: {
    gameTitle: "Civilization of Sands",
    subTitle: "A Strategic Board Game",
    play: "Play",
    events: "Events",
    eventsTitle: "Live Events",
    alliance: "Alliance",
    shop: "Shop",
    social: "Social",
    guide: "Guide",
    settings: "Settings",
    gameLog: "Game Log",

    createAlliance: "Create Alliance",
    joinAlliance: "Join Alliance",
    allianceName: "Alliance Name",
    leaveAlliance: "Leave",
    donate: "Donate",
    treasury: "Treasury",
    members: "Members",
    level: "Level",
    technology: "Technology",
    techTrade: "Trade Routes",
    techDefense: "Fortifications",
    upgrade: "Upgrade",
    allianceEvents: "Alliance Events",
    mission1: "Control 5 Cities",
    mission2: "Collect 10,000 Gold",
    donateMsg: "Donate to Alliance",

    modeSelect: "Select Game Mode",
    modePvE: "Vs CPU",
    modeLocalPvP: "Vs Player (Local)",
    modeOnlinePvP: "Vs Friend (Online)",

    createRoom: "Create Room",
    joinRoom: "Join Room",
    enterCode: "Enter Room Code",
    waitingForPlayer: "Waiting for player...",
    roomCode: "Room Code:",
    shareCode: "Share this code with a friend",

    shopTitle: "City Market",
    skins: "Skins",
    maps: "Maps",
    buy: "Buy",
    owned: "Owned",
    equip: "Equip",
    equipped: "Equipped",

    chat: "Chat",
    globalChat: "Global Chat",

    howToPlay: "How to Play",
    rule1: "Roll dice to move across cities.",
    rule2: "Buy cities to collect rent.",
    rule3: "Watch out for storms and taxes!",
    rule4: "Use your character ability to win.",

    back: "Back",
    start: "Start",
    language: "Language",
    targetGold: "Winning Gold Target",
    sound: "Sound Effects",
    saveReturn: "Save & Return",
    chooseLeader: "Choose Your Leader",
    turn: "TURN",
    status: "STATUS",
    rollDice: "ROLL DICE",
    pass: "Pass",
    payRent: "Pay Rent",
    taxPaid: "Tax Paid",
    jailMsg: "In Jail!",
    freeMsg: "Is Free!",
    win: "VICTORY!",
    lost: "BANKRUPT",
    playAgain: "Play Again",
    finalStats: "Final Stats",
    properties: "Properties",
    gold: "Gold",
    water: "Water",
    energy: "Energy",
    materials: "Materials",
    eventStorm: "Sandstorm",
    eventCaravan: "Merchant Caravan",
    eventMirage: "Mirage",
    eventTreasure: "Treasure",
    oracleSpeaks: "The Oracle Speaks",
    acceptFate: "Accept Fate",
    buyWater: "Buy Water",
    buyMat: "Buy Materials",
    guideCaravan: "Guide Caravan",
    dismiss: "Dismiss",
    cost: "Cost",
    rent: "Rent",
    startBonus: "Start Bonus",
    rolled: "rolled",
    START: "Start",
    EVENT_STORM: "Storm",
    OASIS_PALM: "Palm Oasis",
    TAX_SULTAN: "Sultan's Tax",
    ORACLE_SAGE: "The Sage",
    JAIL: "Dungeon",
    EVENT_CARAVAN: "Caravan",
    OASIS_WELL: "Old Well",
    ORACLE_LIB: "Library",
    TAX_WATER: "Water Tax"
  }
};
